services:
  - type: web
    name: arweaventegra
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: testnet
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ARWEAVE_WALLET_JWK
        sync: false 